<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mwtest</string>
	</array>
	<key>name</key>
	<string>MWParserFromHell Test Case</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>---</string>
			<key>name</key>
			<string>markup.heading.divider.mwpfh</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.mwpfh</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.name.mwpfh</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(name:)\s*(\w*)</string>
			<key>name</key>
			<string>meta.name.mwpfh</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.label.mwpfh</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.other.label.mwpfh</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(label:)\s*(.*)</string>
			<key>name</key>
			<string>meta.label.mwpfh</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.input.mwpfh</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.input.mwpfh</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(input:)\s*(.*)</string>
			<key>name</key>
			<string>meta.input.mwpfh</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.output.mwpfh</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(output:)</string>
			<key>name</key>
			<string>meta.output.mwpfh</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.language.token.mwpfh</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+)\s*\(</string>
			<key>name</key>
			<string>meta.name.token.mwpfh</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.token.mwpfh</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+)\s*(=)</string>
			<key>name</key>
			<string>meta.name.parameter.token.mwpfh</string>
		</dict>
		<dict>
			<key>match</key>
			<string>".*?"</string>
			<key>name</key>
			<string>string.quoted.double.mwpfh</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.mwpfh</string>
	<key>uuid</key>
	<string>cd3e2ffa-a57d-4c40-954f-1a2e87ffd638</string>
</dict>
</plist>
